# Generated by Django 2.2.14 on 2021-08-27 06:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_services'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Services',
            new_name='Service',
        ),
    ]
